---
name: CI
"on": [pull_request]
defaults:
  run:
    shell: bash
jobs:
  pr:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - name: checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: run the build
        run: ./mach build
